info:
  contact: {}
  license: {}
paths:
  /api/v1/tags:
    get:
      parameters:
      - description: 标签
        in: query
        name: name
        required: true
        type: string
      - description: 状态
        in: query
        name: state
        type: integer
      responses:
        "200":
          description: '{"code":200,"data":{},"msg":"ok"}'
          schema:
            type: string
      summary: 获取多个文章标签
    post:
      parameters:
      - description: 标签
        in: query
        name: name
        required: true
        type: string
      - description: 状态
        in: query
        name: state
        type: integer
      - description: 创建者
        in: query
        name: created_by
        type: integer
      responses:
        "200":
          description: '{"code":200,"data":{},"msg":"ok"}'
          schema:
            type: string
      summary: 新增文章标签
swagger: "2.0"
